export const firstdata = [
    {
        "date": 1719587304,
        "domain": "www.nbcnews.com",
        "image": "https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2024-04/240416-joseph-fischer-january-6-se-545p-38e4c0.jpg",
        "isVideo": false,
        "link": "https://www.nbcnews.com/politics/supreme-court/supreme-court-rules-jan-6-rioter-challenging-obstruction-char-rcna155902",
        "preview": "The Supreme Court ruled in favor of a former police officer who is seeking to throw out an obstruction charge for joining the Capitol riot on Jan.",
        "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.nbcnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "NBC News",
        "relatedArticles": [{
            "date": 1719586358,
            "domain": "www.foxnews.com",
            "image": "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2024/01/1200/675/january-6-capitol-riot.jpg?ve=1&tl=1",
            "isVideo": false,
            "link": "https://www.foxnews.com/politics/supreme-court-rules-favor-jan-6-capitol-riot-participant-challenged-obstruction-conviction",
            "preview": "The Supreme Court issued a ruling in the case of a January 6 Capitol riot participant who challenged his criminal conviction for obstruction.",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.foxnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "Fox News",
            "title": "Supreme Court rules in favor of Jan. 6 Capitol riot participant who challenged obstruction conviction",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2p2bGNubkN4RXFEQk4zbjRDb19DZ0FQAQ"
        }, {
            "date": 1719586962,
            "domain": "www.cnn.com",
            "image": "https://media.cnn.com/api/v1/images/stellar/prod/240416143527-joan-biskupic.jpg?c=16x9&q=w_1280,c_fill",
            "isVideo": false,
            "link": "https://www.cnn.com/politics/live-news/supreme-court-january-6-ruling-06-28-24/index.html",
            "preview": "The Supreme Court has issued a decision on the January 6 rioters case. Follow here for the latest live news updates, analysis and more.",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "CNN",
            "title": "Live updates: Supreme Court ruling on Jan. 6 rioters case",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2p2bGNubkN4RXFEQk4zbjRDb19DZ0FQAQ"
        }, {
            "date": 1719587712,
            "domain": "www.washingtonpost.com",
            "image": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/GJ5XY5VG4P7LJ35SLMXLCYSNAU_size-normalized.jpg&w=1440",
            "isVideo": false,
            "link": "https://www.washingtonpost.com/politics/2024/06/28/supreme-court-obstruction-jan-6-trump/",
            "preview": "Federal prosecutors improperly charged hundreds of Jan. 6 defendants with obstruction, a divided Supreme Court ruled on Friday, upending many cases against ...",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.washingtonpost.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The Washington Post",
            "title": "Supreme Court says prosecutors improperly charged hundreds of Jan. 6 rioters",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2p2bGNubkN4RXFEQk4zbjRDb19DZ0FQAQ"
        }],
        "title": "Supreme Court rules for Jan. 6 rioter challenging obstruction charge",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2p2bGNubkN4RXFEQk4zbjRDb19DZ0FQAQ"
    },
    {
        "date": 1719586260,
        "domain": "apnews.com",
        "image": "https://dims.apnews.com/dims4/default/d23fefe/2147483647/strip/true/crop/5813x3875+0+0/resize/599x399!/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2F51%2F3f%2F6f0378b6dd9a5236d979f8a34b27%2F28e6b41976cf49d89f356914c289d771",
        "isVideo": false,
        "link": "https://apnews.com/article/supreme-court-chevron-regulations-environment-5173bc83d3961a7aaabe415ceaf8d665",
        "preview": "The Supreme Court has upended a 40-year-old decision that made it easier for the federal government to regulate the environment, public health, ...",
        "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://apnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "The Associated Press",
        "relatedArticles": [{
            "date": 1719589500,
            "domain": "www.nytimes.com",
            "image": "https://static01.nyt.com/images/2024/05/28/multimedia/28scotus-chevron-tbpl/28scotus-chevron-tbpl-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
            "isVideo": false,
            "link": "https://www.nytimes.com/live/2024/06/28/us/supreme-court-chevron",
            "preview": "The foundational 1984 decision required courts to defer to agencies' reasonable interpretations of ambiguous statutes, underpinning regulations on health ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.nytimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The New York Times",
            "title": "Supreme Court Overrules Chevron Doctrine: Live Updates",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2l5dnNQeEN4SHBBVlNYNFVsckhpZ0FQAQ"
        }, {
            "date": 1719585311,
            "domain": "www.nbcnews.com",
            "image": "https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2024-04/240411-supreme-court-ch-1348-9c3eff.jpg",
            "isVideo": false,
            "link": "https://www.nbcnews.com/politics/supreme-court/supreme-court-delivers-blow-power-federal-agencies-rcna145344",
            "preview": "The Supreme Court overturned a 40-year-old precedent that has been a target of the right because it is seen as bolstering the power of \"deep state\" ...",
            "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.nbcnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "NBC News",
            "title": "Supreme Court delivers blow to power of federal agencies, overturning 40-year-old precedent",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2l5dnNQeEN4SHBBVlNYNFVsckhpZ0FQAQ"
        }, {
            "date": 1719585660,
            "domain": "www.cnn.com",
            "image": "https://media.cnn.com/api/v1/images/stellar/prod/ap24178521558163-copy.jpg?c=16x9&q=h_833,w_1480,c_fill",
            "isVideo": false,
            "link": "https://www.cnn.com/2024/06/28/politics/chevron-precedent-supreme-court/index.html",
            "preview": "The Supreme Court significantly weakened the power of federal agencies to approve regulations in a major decision Friday that could have sweeping ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "CNN",
            "title": "Supreme Court overturns 1984 Chevron precedent, curbing power of federal government",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2l5dnNQeEN4SHBBVlNYNFVsckhpZ0FQAQ"
        }],
        "title": "The Supreme Court weakens federal regulators, overturning decades-old Chevron decision",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2l5dnNQeEN4SHBBVlNYNFVsckhpZ0FQAQ"
    },
    {
        "date": 1719586680,
        "domain": "www.cnn.com",
        "image": "https://media.cnn.com/api/v1/images/stellar/prod/ats20708.jpg?c=16x9&q=h_438,w_780,c_fill",
        "isVideo": false,
        "link": "https://www.cnn.com/election/2024/analysis-commentary-cnn-debate",
        "preview": "Read CNN's analysis and commentary of the first 2024 presidential debate between President Joe Biden and former President Donald Trump in Atlanta.",
        "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "CNN",
        "relatedArticles": [{
            "date": 1719582360,
            "domain": "www.nytimes.com",
            "image": "https://static01.nyt.com/images/2024/07/27/multimedia/27dc-assess-top-sub-fvqz/27dc-assess-top-sub-fvqz-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
            "isVideo": false,
            "link": "https://www.nytimes.com/2024/06/27/us/politics/biden-debate-democrats.html",
            "preview": "President Biden hoped to build fresh momentum for his re-election bid by agreeing to debate nearly two months before he is to be formally nominated.",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.nytimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The New York Times",
            "title": "Biden’s Shaky Debate Performance Has Democrats Panicking",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pRZzVybkN4RlVqQXFGUW1IalV5Z0FQAQ"
        }, {
            "date": 1719585432,
            "domain": "www.npr.org",
            "image": "https://npr.brightspotcdn.com/dims3/default/strip/false/crop/4856x3642+304+0/resize/1100/quality/50/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F1f%2F5f%2F17d2ad084b84b5110b8b78769e95%2Fap24180094773783.jpg",
            "isVideo": false,
            "link": "https://www.npr.org/2024/06/28/g-s1-7055/democrats-struggle-biden-debate-performance",
            "preview": "Democrats spent the hours following the first presidential debate dodging questions about President Biden's fitness to lead the party and struggling to ...",
            "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.npr.org&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "NPR",
            "title": "Democrats struggle to respond to Biden debate performance",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pRZzVybkN4RlVqQXFGUW1IalV5Z0FQAQ"
        }, {
            "date": 1719570480,
            "domain": "apnews.com",
            "image": "https://assets.apnews.com/bc/a2/a1c8c29c2e06c65dc3fc68b019f2/42e710a523764dd4b18945db4edda00e",
            "isVideo": false,
            "link": "https://apnews.com/article/fact-check-misinformation-election-debate-trump-biden-577507522762aa10f6ee5be3a0ced2bb",
            "preview": "The Associated Press examines false and misleading statements made by Donald Trump and Joe Biden as they prepare to face off in the Election 2024 ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://apnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The Associated Press",
            "title": "Biden-Trump debate: Here are the false claims made during the faceoff",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pRZzVybkN4RlVqQXFGUW1IalV5Z0FQAQ"
        }],
        "title": "Analysis and commentary on CNN’s presidential debate",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pRZzVybkN4RlVqQXFGUW1IalV5Z0FQAQ"
    },
    {
        "date": 1719580867,
        "domain": "www.axios.com",
        "image": "https://images.axios.com/853F4hVRoWDk25uJv8gyHyGnGh0=/0x307:3309x2169/1920x1080/2024/06/28/1719578351511.jpg?w=1920",
        "isVideo": false,
        "link": "https://www.axios.com/2024/06/28/who-replace-biden-2024-election-democrats",
        "preview": "No party in modern U.S. history has ever tried to forcibly replace its presidential nominee.",
        "pubLogo": "https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.axios.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "Axios",
        "relatedArticles": [{
            "date": 1719554248,
            "domain": "www.nytimes.com",
            "image": "https://static01.nyt.com/images/2024/06/28/multimedia/28friedman-cwbf/28friedman-cwbf-articleLarge-v4.jpg?quality=75&auto=webp&disable=upscale",
            "isVideo": false,
            "link": "https://www.nytimes.com/2024/06/28/opinion/joe-biden-tom-friedman.html",
            "preview": "Donald Trump is too grave a threat to America. Democrats need a nominee who can unite the country and articulate a compelling vision for it.",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.nytimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The New York Times",
            "title": "Opinion | Joe Biden Is a Good Man and a Good President. He Must Bow Out of the Race.",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pTcllYekN4RWwxR2oxSlVqZjV5Z0FQAQ"
        }, {
            "date": 1719589800,
            "domain": "www.theatlantic.com",
            "image": "https://cdn.theatlantic.com/thumbor/Hh_YfNkMrIyJ-gnFEn3716k-MzE=/0x0:5936x3339/960x540/media/img/mt/2024/06/GettyImages_2159607483/original.jpg",
            "isVideo": false,
            "link": "https://www.theatlantic.com/politics/archive/2024/06/great-democratic-conundrum-biden/678830/",
            "preview": "How to replace the presidential candidate without tearing the party apart and losing the election anyway.",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.theatlantic.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The Atlantic",
            "title": "The Great Democratic Conundrum",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pTcllYekN4RWwxR2oxSlVqZjV5Z0FQAQ"
        }, {
            "date": 1719576900,
            "domain": "www.cnn.com",
            "image": "https://media.cnn.com/api/v1/images/stellar/prod/240627211015-13-gallery-biden-trump-cnn-debate-062724.jpg?c=16x9&q=h_833,w_1480,c_fill",
            "isVideo": false,
            "link": "https://www.cnn.com/2024/06/28/politics/election-biden-presidential-race-what-matters/index.html",
            "preview": "Joe Biden's spotty debate performance immediately triggered new questions from worried Democrats about whether he would leave the presidential race.",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "CNN",
            "title": "What would happen if Biden decided to leave the race?",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pTcllYekN4RWwxR2oxSlVqZjV5Z0FQAQ"
        }],
        "title": "Who Democrats could choose to replace Biden after his disastrous debate",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pTcllYekN4RWwxR2oxSlVqZjV5Z0FQAQ"
    },
    {
        "date": 1719583578,
        "domain": "www.npr.org",
        "image": "https://npr.brightspotcdn.com/dims3/default/strip/false/crop/4947x3298+0+0/resize/1100/quality/50/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F0f%2Fb6%2F1acc4d154a438b1783189b17d7ab%2Fap24105353378147.jpg",
        "isVideo": false,
        "link": "https://www.npr.org/2024/06/28/nx-s1-4992010/supreme-court-homeless-punish-sleeping-encampments",
        "preview": "In its biggest decision on homelessness in decades, the U.S. Supreme Court today ruled that cities can ban people from sleeping and camping in public places ...",
        "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.npr.org&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "NPR",
        "relatedArticles": [{
            "date": 1719584910,
            "domain": "www.nytimes.com",
            "image": "https://static01.nyt.com/images/2024/06/28/multimedia/28scotus-homelessness-header-zlqb/28scotus-homelessness-header-zlqb-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
            "isVideo": false,
            "link": "https://www.nytimes.com/2024/06/28/us/politics/supreme-court-homelessness.html",
            "preview": "The Supreme Court on Friday upheld an Oregon city's laws aimed at banning homeless residents from sleeping outdoors, saying they did not violate the ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.nytimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The New York Times",
            "title": "Supreme Court Upholds Ban on Sleeping Outdoors in Homelessness Case",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lUbDZMeEN4RzBIRUItWUlad1VDZ0FQAQ"
        }, {
            "date": 1719590452,
            "domain": "www.bloomberg.com",
            "image": "https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iUTETot3DVPI/v1/-1x-1.jpg",
            "isVideo": false,
            "link": "https://www.bloomberg.com/news/articles/2024-06-28/what-the-supreme-court-encampments-decision-means-for-homeless-people?srnd=equality",
            "preview": "The Supreme Court ruling in Grants Pass lets lawmakers impose fines and jail time on homeless people sleeping outside.",
            "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.bloomberg.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "Bloomberg",
            "title": "What the Supreme Court Encampments Decision Means for Homeless People",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lUbDZMeEN4RzBIRUItWUlad1VDZ0FQAQ"
        }, {
            "date": 1719584700,
            "domain": "www.wsj.com",
            "image": "https://images.wsj.net/im-971830?width=700&height=466",
            "isVideo": false,
            "link": "https://www.wsj.com/us-news/law/supreme-court-homeless-camps-f3c68a9a",
            "preview": "WASHINGTONThe Supreme Court loosened the restraints on city officials confronting homeless encampments, overturning a lower court that found it ...",
            "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.wsj.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The Wall Street Journal",
            "title": "Supreme Court Expands Cities' Power to Remove Homeless Camps",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lUbDZMeEN4RzBIRUItWUlad1VDZ0FQAQ"
        }],
        "title": "Supreme Court allows punishment for homeless sleeping",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lUbDZMeEN4RzBIRUItWUlad1VDZ0FQAQ"
    },


]

export const seconddata = [
    {
        "date": 1719576693,
        "domain": "www.npr.org",
        "image": "https://npr.brightspotcdn.com/dims3/default/strip/false/crop/7339x5504+0+0/resize/1100/quality/50/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F4d%2F57%2F5bf267d7446994fb276d573c0676%2Fgettyimages-2158500442.jpg",
        "isVideo": false,
        "link": "https://www.npr.org/sections/shots-health-news/2024/06/28/nx-s1-5021863/idaho-abortion-emergency-supreme-court-case-reaction",
        "preview": "The decision on abortion that the Supreme Court handed down Thursday was narrow. But confusion for doctors in abortion ban states about how to deal with ...",
        "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.npr.org&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "NPR",
        "relatedArticles": [{
            "date": 1719505117,
            "domain": "www.usatoday.com",
            "image": "https://www.usatoday.com/gcdn/authoring/authoring-images/2024/06/26/USAT/74222237007-20240624-t-205633-z-1139263174-rc-2-uh-8-almomk-rtrmadp-3-usaabortionanniversaryprotest.JPG?crop=5790,3258,x0,y301&width=660&height=371&format=pjpg&auto=webp",
            "isVideo": false,
            "link": "https://www.usatoday.com/story/news/health/2024/06/27/supreme-court-emergency-abortion-decision-dismayed-reaction/74203649007/",
            "preview": "Both abortion advocates and opponents expressed disappointment after the Supreme Court allowed emergency abortions in Idaho, as litigation continues.",
            "pubLogo": "https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.usatoday.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "USA TODAY",
            "title": "Supreme Court abortion decision frustrates both sides",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lLLXVEbkN4R2lXWmlCWFVCTElpZ0FQAQ"
        }, {
            "date": 1719588661,
            "domain": "theintercept.com",
            "image": "https://theintercept.com/wp-content/uploads/2024/06/GettyImages-2149405616-e1719581442674.jpg?fit=8256%2C4128",
            "isVideo": false,
            "link": "https://theintercept.com/2024/06/28/emtala-supreme-court-decision-alito/",
            "preview": "Despite deciding not to decide, the Supreme Court's conservative supermajority laid out a legal road map for anti-abortion zealots.",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://theintercept.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The Intercept",
            "title": "Alito's Dissent in Emergency Abortion Case Provides “Building Blocks” for More Extreme Bans",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lLLXVEbkN4R2lXWmlCWFVCTElpZ0FQAQ"
        }, {
            "date": 1719523620,
            "domain": "www.nytimes.com",
            "image": "https://static01.nyt.com/images/2024/06/07/multimedia/00dc-scotus-emtala-tjzp/00dc-scotus-emtala-tjzp-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
            "isVideo": false,
            "link": "https://www.nytimes.com/2024/06/27/us/politics/supreme-court-idaho-abortion.html",
            "preview": "The Supreme Court said on Thursday that it would dismiss a case about emergency abortions in Idaho, temporarily clearing the way for women in the state to ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.nytimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The New York Times",
            "title": "Supreme Court Allows, for Now, Emergency Abortions in Idaho",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lLLXVEbkN4R2lXWmlCWFVCTElpZ0FQAQ"
        }],
        "title": "Abortion bans still leave a 'gray area' for doctors after Idaho Supreme Court case",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lLLXVEbkN4R2lXWmlCWFVCTElpZ0FQAQ"
    },
    {
        "date": 1719562753,
        "domain": "www.npr.org",
        "image": "https://npr.brightspotcdn.com/dims3/default/strip/false/crop/1900x1425+5+0/resize/1100/quality/50/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F9c%2F53%2Fb340995d4a16962f2a038d0182ff%2Fap24179569961270.jpg",
        "isVideo": false,
        "link": "https://www.npr.org/2024/06/28/g-s1-6955/giant-sinkhole-soccer-field",
        "preview": "ALTON, Ill.  A giant sinkhole has swallowed the center of a soccer complex that was built over an operating limestone mine in southern Illinois, ...",
        "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.npr.org&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "NPR",
        "relatedArticles": [{
            "date": 1719525900,
            "domain": "www.cnn.com",
            "image": "https://media.cnn.com/api/v1/images/stellar/prod/thumbnail-20240627151820532.jpg?c=16x9&q=w_1280,c_fill",
            "isVideo": false,
            "link": "https://www.cnn.com/2024/06/27/us/video/massive-sinkhole-soccer-field-alton-illinois-digvid",
            "preview": "A massive sinkhole opened up at a soccer field and swallowed a light pole after a mine underground collapsed in Alton, Illinois.",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "CNN",
            "title": "Dramatic video shows a 100-foot-wide sinkhole open up at park",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kyaThEeEN4RllfWlR0M3Rubzh5Z0FQAQ"
        }, {
            "date": 1719495885,
            "domain": "weather.com",
            "image": "https://s.w-x.co/SoccerSinkhole3.jpg?crop=16:9&width=320&format=pjpg&auto=webp&quality=60",
            "isVideo": false,
            "link": "https://weather.com/news/video/massive-sinkhole-swallows-part-of-illinois-soccer-field",
            "preview": "A soccer field at an Illinois park won't be open for awhile after a huge sinkhole opened in the middle of the field. Watch the stunning video and learn what ...",
            "pubLogo": "https://encrypted-tbn0.gstatic.com/faviconV2?url=https://weather.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The Weather Channel",
            "title": "Sinkhole Swallows Part Of Illinois Soccer Field - Videos from The Weather Channel",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kyaThEeEN4RllfWlR0M3Rubzh5Z0FQAQ"
        }, {
            "date": 1719441240,
            "domain": "www.bnd.com",
            "image": "https://www.bnd.com/latest-news/8pnj1p/picture289564736/alternates/FREE_1140/06.26.24_Sinkhole_Carter-2.jpg",
            "isVideo": false,
            "link": "https://www.bnd.com/news/local/article289564256.html",
            "preview": "A large sinkhole caused by an collapsed underground mine destroyed a large section of the Gordon F. Moore soccer park at 8:30 a.m. on Wednesday.",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.bnd.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "Belleville News-Democrat",
            "title": "Here’s a look at the crater left behind by a collapsed mine on an Alton soccer field",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kyaThEeEN4RllfWlR0M3Rubzh5Z0FQAQ"
        }],
        "title": "Giant sinkhole swallows the center of a soccer field built on top of a limestone mine",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kyaThEeEN4RllfWlR0M3Rubzh5Z0FQAQ"
    },
    {
        "date": 1719533512,
        "domain": "www.bbc.com",
        "image": "https://ichef.bbci.co.uk/news/1024/branded_news/5222/live/64c77130-34b2-11ef-8557-bbe6d78d7b76.jpg",
        "isVideo": false,
        "link": "https://www.bbc.com/news/articles/c98qgw8qxq7o",
        "preview": "A snap election called after a deadly helicopter crash. A candidate promising a different approach both at home and abroad. And suddenly there's an element ...",
        "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.bbc.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "BBC.com",
        "relatedArticles": [{
            "date": 1719578160,
            "domain": "www.cnn.com",
            "image": "https://media.cnn.com/api/v1/images/stellar/prod/gettyimages-2157491264.jpg?c=16x9&q=h_833,w_1480,c_fill",
            "isVideo": false,
            "link": "https://www.cnn.com/2024/06/28/middleeast/iran-presidential-election-june-28-mime-intl/index.html",
            "preview": "Under the specter of conflict with Israel, a struggling economy and social discontent, Iranians headed to the polls on Friday for snap presidential ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "CNN",
            "title": "Iranians vote for a new president under the shadow of conflict and economic woes",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pCemJ6ckN4R2N6QVFodEY2WnVDZ0FQAQ"
        }, {
            "date": 1719588581,
            "domain": "www.nbcnews.com",
            "image": "https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2024-06/240628-iran-election-mb-1227-3ee91d.jpg",
            "isVideo": false,
            "link": "https://www.nbcnews.com/news/world/iran-election-votes-president-raisi-rcna159399",
            "preview": "Millions of Iranians are heading to the polls Friday in a snap election called after President Ebrahim Raisi died in a helicopter crash last month.",
            "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.nbcnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "NBC News",
            "title": "Iran election: Islamic Republic votes to replace late President Raisi",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pCemJ6ckN4R2N6QVFodEY2WnVDZ0FQAQ"
        }, {
            "date": 1719547278,
            "domain": "www.nytimes.com",
            "image": "https://static01.nyt.com/images/2024/06/27/multimedia/27iran-candidates-01-clgz/27iran-candidates-01-clgz-mediumSquareAt3X.jpg",
            "isVideo": false,
            "link": "https://www.nytimes.com/2024/06/28/world/middleeast/irans-presidential-candidates.html",
            "preview": "Four of the six candidates selected by officials to run in Iran's special presidential election are still in the running after the president died in a ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.nytimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The New York Times",
            "title": "Iran's Presidential Candidates: Who Are They?",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pCemJ6ckN4R2N6QVFodEY2WnVDZ0FQAQ"
        }],
        "title": "Iran: Wildcard candidate stirs up presidential election",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pCemJ6ckN4R2N6QVFodEY2WnVDZ0FQAQ"
    },
    {
        "date": 1719575195,
        "domain": "www.nbcnews.com",
        "image": "https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2024-06/240628-kadena-air-base-japan-mb-1125-747248.jpg",
        "isVideo": false,
        "link": "https://www.nbcnews.com/news/us-news/us-airmen-charged-sexual-assaults-japan-okinawa-rcna159393",
        "preview": "TOKYO  Japanese authorities have charged two U.S..",
        "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.nbcnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "NBC News",
        "relatedArticles": [{
            "date": 1719475500,
            "domain": "www.cnn.com",
            "image": "https://media.cnn.com/api/v1/images/stellar/prod/2023-08-24t011918z-1792668356-rc2zt2a8ljfx-rtrmadp-3-northkorea-missiles.jpg?c=16x9&q=h_833,w_1480,c_fill",
            "isVideo": false,
            "link": "https://www.cnn.com/2024/06/27/asia/us-air-force-rape-japanese-schoolgirl-intl-hnk/index.html",
            "preview": "Japanese prosecutors have charged a US Air Force member with allegedly kidnapping and raping an underage girl just before Christmas last year, ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "CNN",
            "title": "US Air Force member charged with kidnapping and raping Japanese schoolgirl",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lfMTdId0N4RkNVcUpnR0JTYml5Z0FQAQ"
        }, {
            "date": 1719570052,
            "domain": "abcnews.go.com",
            "image": "https://s.abcnews.com/images/US/wirestory_93df092f43e2494d122b562145f10956_16x9_1600.jpg",
            "isVideo": false,
            "link": "https://abcnews.go.com/International/wireStory/japan-protests-sex-assault-cases-involving-us-military-111506782",
            "preview": "Japan's government has protested to the U.S. Embassy in Tokyo over at least two sexual assault cases involving American servicemembers on the southern ...",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://abcnews.go.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "ABC News",
            "title": "Japan protests sex assault cases involving US military on Okinawa and their delayed disclosure",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lfMTdId0N4RkNVcUpnR0JTYml5Z0FQAQ"
        }, {
            "date": 1719590700,
            "domain": "thehill.com",
            "image": "https://thehill.com/wp-content/uploads/sites/2/2017/04/japan_flag_617319960.jpg?strip=1",
            "isVideo": false,
            "link": "https://thehill.com/policy/defense/4745833-us-military-accused-sexual-assault-japan/",
            "preview": "Two U.S. members of the armed services have been accused of sexual assault in Japan, spurring Japanese officials to speak out against what they have called ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://thehill.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The Hill",
            "title": "Two US serviced members charged with sexual assault in Japan",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lfMTdId0N4RkNVcUpnR0JTYml5Z0FQAQ"
        }],
        "title": "Two U.S. airmen charged with separate sexual assaults in Japan",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lfMTdId0N4RkNVcUpnR0JTYml5Z0FQAQ"
    },
    {
        "date": 1719583319,
        "domain": "www.npr.org",
        "image": "https://npr.brightspotcdn.com/dims3/default/strip/false/crop/3691x2768+171+0/resize/1100/quality/50/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F9f%2Fc4%2F608167384cf8b9df48bcf47281c7%2Fap24102770511149.jpg",
        "isVideo": false,
        "link": "https://www.npr.org/2024/06/27/nx-s1-5021942/abortion-six-week-ban-iowa-dobbs",
        "preview": "Iowa is set to become the latest state to tightly restrict accessto abortion after the state's supreme court upheld a law banning abortions at six weeks of ...",
        "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.npr.org&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "NPR",
        "relatedArticles": [{
            "date": 1719586740,
            "domain": "www.cnn.com",
            "image": "https://media.cnn.com/api/v1/images/stellar/prod/c-ap22168523451473.jpg?c=16x9&q=h_833,w_1480,c_fill",
            "isVideo": false,
            "link": "https://www.cnn.com/2024/06/28/politics/iowa-supreme-court-abortion-ban/index.html",
            "preview": "The Iowa Supreme Court ruled Friday to uphold the state's abortion ban, which prohibits most abortions in the state as early as six weeks into pregnancy.",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "CNN",
            "title": "Iowa Supreme Court upholds state’s 6-week abortion ban",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pvdy1fb0N4RVBiZXlHczBDVGJDZ0FQAQ"
        }, {
            "date": 1719510970,
            "domain": "www.bbc.com",
            "image": "https://ichef.bbci.co.uk/news/480/cpsprodpb/61b3/live/558d2590-3564-11ef-b6d9-e13f185918e1.jpg.webp",
            "isVideo": false,
            "link": "https://www.bbc.com/news/articles/cpd9r9g192lo",
            "preview": "Iowa's highest court has upheld a law saying the state can enforce a ban on most abortions after about six weeks of pregnancy. The law bans abortions after ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.bbc.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "BBC.com",
            "title": "US abortion: Iowa's top court upholds six-week abortion ban law",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pvdy1fb0N4RVBiZXlHczBDVGJDZ0FQAQ"
        }, {
            "date": 1719583560,
            "domain": "www.kcci.com",
            "image": "https://hips.hearstapps.com/vidthumb/e1baa91d-5680-408d-bcba-396f19868745/c15e5472-2f5c-4d5e-b84e-491635c2f700.jpg?crop=1xw%3A1.0xh%3Bcenter%2Ctop&resize=810%3A*&quality=70",
            "isVideo": false,
            "link": "https://www.kcci.com/article/iowa-supreme-court-decision-upholds-abortion-ban-ruling-fetal-heartbeat-decision-six-weeks/61240552",
            "preview": "The Iowa Supreme Court upheld an abortion law Friday that bans abortions once fetal cardiac activity is detected. Doctors say that is typically at six weeks ...",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.kcci.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "KCCI Des Moines",
            "title": "Iowa abortion ban: Supreme Court decision upholds fetal heartbeat law",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pvdy1fb0N4RVBiZXlHczBDVGJDZ0FQAQ"
        }],
        "title": "Iowa supreme court upholds ban on abortion at six weeks of pregnancy",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2pvdy1fb0N4RVBiZXlHczBDVGJDZ0FQAQ"
    },
]

export const thirddata = [
    {
        "date": 1719551040,
        "domain": "apnews.com",
        "image": "https://dims.apnews.com/dims4/default/20ddf9b/2147483647/strip/true/crop/3617x2412+0+0/resize/599x399!/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2Fcb%2F9d%2Fdece23cbfce9891601d056631ee4%2F72bab9e353e447279712a604670e8703",
        "isVideo": false,
        "link": "https://apnews.com/article/karen-read-boston-murder-trial-okeefe-2ee31aa52ba3d76a5eb831f297ac7527",
        "preview": "The woman charged with killing her Boston police officer boyfriend had dated him briefly when they were in their 20s, and they reconnected during the ...",
        "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://apnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "The Associated Press",
        "relatedArticles": [{
            "date": 1719526332,
            "domain": "www.bostonglobe.com",
            "image": "https://bostonglobe-prod.cdn.arcpublishing.com/resizer/v2/V4CMKSFTMLSXIYZVEJBFQ3NUDI.jpg?auth=962a8d47e1e4298ba795852283ebc7ec1b168c7ef313ffddb084d55fa4988901&width=1440",
            "isVideo": false,
            "link": "https://www.bostonglobe.com/2024/06/27/metro/karen-read-trial-canton-divisions/",
            "preview": "CANTON  The Rev. John Tamilio III, the pastor of the Congregational Church of Canton, has watched the murder case against Karen Read tear his community in ...",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.bostonglobe.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The Boston Globe",
            "title": "Can Canton recover from divisions of Karen Read trial?",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lYanFIc0N4SFFPdEdJSmxBZUZTZ0FQAQ"
        }, {
            "date": 1719579840,
            "domain": "www.boston.com",
            "image": "https://bdc2020.o0bc.com/wp-content/uploads/2024/06/s3___bgmp-arc_arc-feeds_generic-photos_to-arc_tlumackikarenread618-667eb1de6e85c-scaled.jpg",
            "isVideo": false,
            "link": "https://www.boston.com/news/crime/2024/06/28/karen-read-trial-jury-no-verdict-meaning/",
            "preview": "Jurors are entering their fourth day of deliberations in the Karen Read trial after heading home Thursday without a verdict.",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.boston.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "Boston.com",
            "title": "Karen Read trial: Jurors have yet to return a verdict. Here’s what that could mean.",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lYanFIc0N4SFFPdEdJSmxBZUZTZ0FQAQ"
        }, {
            "date": 1719431234,
            "domain": "www.nytimes.com",
            "image": "https://static01.nyt.com/images/2024/06/26/multimedia/26xp-read-wwk-lfmk/26xp-read-wwk-lfmk-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
            "isVideo": false,
            "link": "https://www.nytimes.com/2024/06/26/us/karen-read-murder-trial.html",
            "preview": "Jury deliberations began on Tuesday in the murder trial of Karen Read, who is accused of intentionally backing her vehicle into her boyfriend, ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.nytimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The New York Times",
            "title": "What We Know About the Karen Read Murder Trial",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lYanFIc0N4SFFPdEdJSmxBZUZTZ0FQAQ"
        }],
        "title": "Karen Read once 'admired' the Boston police boyfriend she's accused of killing",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lYanFIc0N4SFFPdEdJSmxBZUZTZ0FQAQ"
    },
    {
        "date": 1719581700,
        "domain": "www.nbcnews.com",
        "image": "https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2022-05/220527-Robb-Elementary-School-al-1446-ac0933.jpg",
        "isVideo": false,
        "link": "https://www.nbcnews.com/news/us-news/former-uvalde-school-district-police-chief-charged-child-endangerment-rcna134848",
        "preview": "Pete Arredondo, the former police chief of the Uvalde Consolidated Independent School District, was charged with abandoning and endangering a child.",
        "pubLogo": "https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.nbcnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "NBC News",
        "relatedArticles": [{
            "date": 1719584287,
            "domain": "www.expressnews.com",
            "image": "https://s.hdnux.com/photos/01/35/21/27/24450517/5/rawImage.jpg",
            "isVideo": false,
            "link": "https://www.expressnews.com/news/article/arredondo-uvalde-indictment-criminal-negligence-19544332.php",
            "preview": "By bungling the police response to the 2022 mass shooting at Robb Elementary School, Pedro \"Pete\" Arredondo, then chief of the Uvalde school district police ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.expressnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "San Antonio Express-News",
            "title": "Indictment: Pete Arredondo's missteps were 'criminal negligence'",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2k5MThUeUN4R1pjekJTRXZSQVh5Z0FQAQ"
        }, {
            "date": 1719585526,
            "domain": "www.ksat.com",
            "image": "https://res.cloudinary.com/graham-media-group/image/upload/f_auto/q_auto/c_scale,w_400/v1/media/gmg/U5C5BX3EEFFABL5RIC7SRDDK5E.jpg?_a=AJFJtWIA",
            "isVideo": false,
            "link": "https://www.ksat.com/news/local/2024/06/28/10-count-indictment-released-in-case-against-former-uvalde-school-district-chief/",
            "preview": "UVALDE, Texas  Records from a 10-count indictment were released Friday in the case against former Uvalde school district police chief Pete Arredondo.",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.ksat.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "KSAT San Antonio",
            "title": "10-count indictment released in case against former Uvalde school district police chief",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2k5MThUeUN4R1pjekJTRXZSQVh5Z0FQAQ"
        }, {
            "date": 1719587688,
            "domain": "wtop.com",
            "image": "https://wtop.com/wp-content/uploads/2024/06/Uvalde_School_Shooting_Indictments_99410-scaled.jpg",
            "isVideo": false,
            "link": "https://wtop.com/national/2024/06/indictment-accuses-former-uvalde-schools-police-chief-of-delays-while-shooter-was-hunting-children/",
            "preview": "AUSTIN, Texas (AP)  The police chief for schools in Uvalde, Texas, failed to identify an active shooting, did not follow his training and made critical",
            "pubLogo": "https://encrypted-tbn0.gstatic.com/faviconV2?url=https://wtop.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "WTOP",
            "title": "Indictment accuses former Uvalde schools police chief of delays while shooter was “hunting” children",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2k5MThUeUN4R1pjekJTRXZSQVh5Z0FQAQ"
        }],
        "title": "Former Uvalde school district police chief charged with child endangerment after shooting that killed 21",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2k5MThUeUN4R1pjekJTRXZSQVh5Z0FQAQ"
    },
    {
        "date": 1719574500,
        "domain": "www.cnn.com",
        "image": "https://media.cnn.com/api/v1/images/stellar/prod/still-20744192-427126-284-still.jpg?c=16x9&q=w_800,c_fill",
        "isVideo": false,
        "link": "https://www.cnn.com/2024/06/27/politics/video/age-biden-trump-cnn-debate-digvid",
        "preview": "President Joe Biden and former President Donald Trump respond to concerns about their age during the 2024 CNN Presidential Debate.",
        "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.cnn.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "CNN",
        "relatedArticles": [{
            "date": 1719581220,
            "domain": "www.foxnews.com",
            "image": "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2024/06/1200/675/trump-biden-dechambeau.jpg?ve=1&tl=1",
            "isVideo": false,
            "link": "https://www.foxnews.com/sports/us-open-champ-bryson-dechambeau-offers-settle-trump-biden-golf-handicap-debate",
            "preview": "Reigning U.S. Open winner Bryson DeChambeau is looking to settle one issue from Thursday night's presidential debate: What is President Joe Biden's real ...",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.foxnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "Fox News",
            "title": "US Open champ Bryson DeChambeau offers to settle Trump, Biden golf handicap debate",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kwbTlieUN4RWZ1VVozeEdCVlJ5Z0FQAQ"
        }, {
            "date": 1719550740,
            "domain": "slate.com",
            "image": "https://compote.slate.com/images/cceeb3f3-964c-4d6f-8434-5578d088bf5c.jpeg?crop=1560%2C1040%2Cx0%2Cy0",
            "isVideo": false,
            "link": "https://slate.com/culture/2024/06/presidential-debate-winner-trump-biden-reaction-golf.html",
            "preview": "For the first hour and 20 minutes of Thursday night's presidential debate, Joe Biden and Donald Trump gracefully and thoughtfully debated the day's critical ...",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://slate.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "Slate",
            "title": "Presidential debate: An unfortunate reality check about the night's weirdest Trump-Biden exchange.",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kwbTlieUN4RWZ1VVozeEdCVlJ5Z0FQAQ"
        }, {
            "date": 1719544020,
            "domain": "www.11alive.com",
            "image": "https://media.11alive.com/assets/WXIA/images/bca9ce11-ad30-4b6e-96d1-2af0251ffd28/20240628T023743/bca9ce11-ad30-4b6e-96d1-2af0251ffd28_1920x1080.jpg",
            "isVideo": false,
            "link": "https://www.11alive.com/article/news/politics/national-politics/donald-trump-joe-biden-golf-handicaps-swings/85-4f024151-1490-4b5c-bd0b-30cf6caf4ca0",
            "preview": "Here's what a 6 handicap means. Donald Trump also touted his golf game in the debate.",
            "pubLogo": "https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.11alive.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "11Alive.com WXIA",
            "title": "Biden golf handicap: What is a handicap?",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kwbTlieUN4RWZ1VVozeEdCVlJ5Z0FQAQ"
        }],
        "title": "See how Trump and Biden respond when asked about their age during the debate",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kwbTlieUN4RWZ1VVozeEdCVlJ5Z0FQAQ"
    },
    {
        "date": 1719583033,
        "domain": "www.newsnationnow.com",
        "image": "https://www.newsnationnow.com/wp-content/uploads/sites/108/2024/06/NN_DebateNight_Cuomo_1920x1080_NoText_RFK.png?w=1920&h=1080&crop=1",
        "isVideo": false,
        "link": "https://www.newsnationnow.com/politics/debates/live-trump-biden-rfk-debate/",
        "preview": "Biden and Trump are squaring off in the first of two presidential debates. Challenger Robert F. Kennedy Jr. will respond to the questions on X.",
        "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.newsnationnow.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "NewsNation Now",
        "relatedArticles": [{
            "date": 1719583020,
            "domain": "www.foxnews.com",
            "image": "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2023/10/1200/675/RFK-and-Biden-split.jpg?ve=1&tl=1",
            "isVideo": false,
            "link": "https://www.foxnews.com/media/rfk-jr-warns-biden-running-country-panned-debate-performance-scary",
            "preview": "Presidential candidate RFK Jr. warned America is being \"run by anonymous men in lanyards\" after President Biden's struggles at the CNN Presidential Debate.",
            "pubLogo": "https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.foxnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "Fox News",
            "title": "RFK Jr. warns Biden isn't running the country after panned debate performance: 'It's scary'",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lxakpqekN4RXprSEJ3ZE1mSHB5Z0FQAQ"
        }, {
            "date": 1719519891,
            "domain": "www.usatoday.com",
            "image": "https://www.usatoday.com/gcdn/authoring/authoring-images/2024/06/27/USAT/74231299007-usatsi-23627242.jpg?crop=5999,3375,x0,y312&width=660&height=371&format=pjpg&auto=webp",
            "isVideo": false,
            "link": "https://www.usatoday.com/story/news/politics/elections/2024/06/27/what-time-debate-tonight/74230330007/",
            "preview": "President Joe Biden and former President Donald Trump will take the stage Thursday night in Atlanta in the first head-to-head presidential debate of the ...",
            "pubLogo": "https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.usatoday.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "USA TODAY",
            "title": "What time is the 'CNN Presidential Debate' tonight? How to watch",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lxakpqekN4RXprSEJ3ZE1mSHB5Z0FQAQ"
        },
        {
            "date": 1719547041,
            "domain": "www.nytimes.com",
            "image": "https://static01.nyt.com/images/2024/06/27/multimedia/27pol-debate-kennedysupporters1-tgkh/27pol-debate-kennedysupporters1-tgkh-square640.jpg?quality=75&auto=webp",
            "isVideo": false,
            "link": "https://www.nytimes.com/2024/06/27/us/politics/kennedy-biden-trump-debate.html",
            "preview": "Robert F. Kennedy Jr., the independent presidential candidate, was not invited to Thursday's party in Atlanta. But that did not stop him from taking part ...",
            "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.nytimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
            "publisher": "The New York Times",
            "title": "Robert F. Kennedy Jr. Debates Alone, Upset Over Being Left Out",
            "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lxakpqekN4RXprSEJ3ZE1mSHB5Z0FQAQ"
        }],
        "title": "Analysis: Biden, Trump trade barbs at debate; RFK Jr. responds",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lxakpqekN4RXprSEJ3ZE1mSHB5Z0FQAQ"
    },
    {
        "date": 1719576900,
        "domain": "apnews.com",
        "image": "https://dims.apnews.com/dims4/default/e068d46/2147483647/strip/true/crop/3000x1999+0+0/resize/599x399!/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2F65%2Fde%2Ffbe66f970527c15506d6935b4431%2Ff7336a7f6fb2425ab30f5970000b9c32",
        "isVideo": false,
        "link": "https://apnews.com/article/cnn-debate-biden-trump-tapper-bash-ccff5a67e0dfbbb650b78a087ce268e6",
        "preview": "It almost didn't seem to matter that CNN's Dana Bash and Jake Tapper were on stage for the much-awaited presidential debate between Joe Biden and Donald ...",
        "pubLogo": "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://apnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL",
        "publisher": "The Associated Press",
        "title": "How did CNN's moderators do in the Biden-Trump debate? It almost didn't matter that they were there",
        "topicId": "CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2kxdHZud0N4SF9qZDVlV3lGVzZ5Z0FQAQ"
    },
]